# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'boilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for boilerplate
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'GoogleSignIn', '~> 4.2.0'

end
