# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

default_platform :ios

platform :ios do
  before_all do
  end


   lane :push do
      pem(
      generate_p12: true,
      force: true,
      output_path: "../fcm-example/"
      )
   end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
      produce(app_name: 'SSG Frontend Boilerplate')
      sigh
      increment_build_number
      gym(scheme: "prod")      # Build your app
      testflight                # Upload to TestFlight
  end

  lane :icon do
    appicon(
        appicon_path: './boilerplate/Images.xcassets',
        appicon_image_file: 'AppIcon.png',
        appicon_devices: [:ipad, :iphone, :ios_marketing])
  end


  # You can define as many lanes as you want

  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
